### ISSUE TITLE
Simple find() receives error

### ISSUE THREAD

**Issue by moskalyk** [RangerMauve/hyperbeedeebee#3]
Simple code gives following error:

code:
```js
	const doc = await db.collection('example').insert({cid: cid})

	const docs = await db.collection('example').find({cid: cid})
```

error:
```
(node:12899) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'equals' of undefined
    at compareEq (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:595:30)
    at queryCompare (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:547:17)
    at matchesQuery (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:533:10)
    at processDoc (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:434:15)
    at Cursor.[Symbol.asyncIterator] (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:503:48)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Cursor.then (/Users/mgrok/Projects/unicode/reed/threads-server/node_modules/hyperbeedeebee/index.js:383:24)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by RangerMauve** [comment]
Would you be able to make a small repo that reproduces this issue?

**Comment by moskalyk** [comment]
It seems when I change the db name from 'example' to something else, this resolves the error.

Here is the [repo](https://github.com/moskalyk/akashic-records), will close now thank you for taking a look.
